
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;

/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * game.java
 *
 * Created on 25 Mar, 2014, 10:02:38 AM
 */
/**
 *
 * @author RAM
 */
public class game extends javax.swing.JFrame {

    /** Creates new form game */
    public game() {
        initComponents();
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        qq = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        opt1 = new javax.swing.JRadioButton();
        opt2 = new javax.swing.JRadioButton();
        opt3 = new javax.swing.JRadioButton();
        opt4 = new javax.swing.JRadioButton();
        jPanel2 = new javax.swing.JPanel();
        l13 = new javax.swing.JLabel();
        l12 = new javax.swing.JLabel();
        l11 = new javax.swing.JLabel();
        l10 = new javax.swing.JLabel();
        l9 = new javax.swing.JLabel();
        l8 = new javax.swing.JLabel();
        l7 = new javax.swing.JLabel();
        l6 = new javax.swing.JLabel();
        l5 = new javax.swing.JLabel();
        l4 = new javax.swing.JLabel();
        l3 = new javax.swing.JLabel();
        l2 = new javax.swing.JLabel();
        l1 = new javax.swing.JLabel();
        n = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        pic = new javax.swing.JLabel();
        lll = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        q = new javax.swing.JLabel();
        s = new javax.swing.JButton();
        answ = new javax.swing.JLabel();
        ansc = new javax.swing.JLabel();
        s1 = new javax.swing.JButton();
        r1 = new javax.swing.JRadioButton();
        r = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        life = new javax.swing.JTextArea();
        n1 = new javax.swing.JButton();
        c = new javax.swing.JLabel();
        rose = new javax.swing.JLabel();
        n2 = new javax.swing.JButton();
        pic2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        qq.setFont(new java.awt.Font("Bradley Hand ITC", 1, 24));
        qq.setForeground(new java.awt.Color(102, 0, 102));
        qq.setBorder(new javax.swing.border.MatteBorder(null));

        buttonGroup1.add(opt1);
        opt1.setFont(new java.awt.Font("Chiller", 1, 24));
        opt1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                opt1MouseEntered(evt);
            }
        });
        opt1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                opt1ActionPerformed(evt);
            }
        });

        buttonGroup1.add(opt2);
        opt2.setFont(new java.awt.Font("Chiller", 1, 24));
        opt2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                opt2MouseEntered(evt);
            }
        });
        opt2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                opt2ActionPerformed(evt);
            }
        });

        buttonGroup1.add(opt3);
        opt3.setFont(new java.awt.Font("Chiller", 1, 24));
        opt3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                opt3MouseEntered(evt);
            }
        });
        opt3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                opt3ActionPerformed(evt);
            }
        });

        buttonGroup1.add(opt4);
        opt4.setFont(new java.awt.Font("Chiller", 1, 24));
        opt4.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                opt4MouseEntered(evt);
            }
        });
        opt4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                opt4ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(opt3, javax.swing.GroupLayout.PREFERRED_SIZE, 237, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(opt1, javax.swing.GroupLayout.PREFERRED_SIZE, 255, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(39, 39, 39)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(opt4, javax.swing.GroupLayout.DEFAULT_SIZE, 215, Short.MAX_VALUE)
                    .addComponent(opt2, javax.swing.GroupLayout.DEFAULT_SIZE, 215, Short.MAX_VALUE))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(opt2)
                    .addComponent(opt1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 65, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(opt3)
                    .addComponent(opt4))
                .addGap(27, 27, 27))
        );

        l13.setFont(new java.awt.Font("Algerian", 3, 36));
        l13.setForeground(new java.awt.Color(153, 0, 204));
        l13.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));

        l12.setFont(new java.awt.Font("Algerian", 3, 36));
        l12.setForeground(new java.awt.Color(255, 0, 102));
        l12.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));

        l11.setFont(new java.awt.Font("Algerian", 3, 36));
        l11.setForeground(new java.awt.Color(0, 0, 204));
        l11.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));

        l10.setFont(new java.awt.Font("Algerian", 3, 36));
        l10.setForeground(new java.awt.Color(51, 153, 0));
        l10.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));

        l9.setFont(new java.awt.Font("Algerian", 3, 36));
        l9.setForeground(new java.awt.Color(0, 0, 204));
        l9.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));

        l8.setFont(new java.awt.Font("Algerian", 3, 36));
        l8.setForeground(new java.awt.Color(0, 153, 51));
        l8.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));

        l7.setFont(new java.awt.Font("Algerian", 3, 36));
        l7.setForeground(new java.awt.Color(0, 0, 204));
        l7.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));

        l6.setFont(new java.awt.Font("Algerian", 3, 36));
        l6.setForeground(new java.awt.Color(0, 102, 51));
        l6.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED, new java.awt.Color(0, 153, 0), java.awt.Color.green, java.awt.Color.green, java.awt.Color.green));

        l5.setFont(new java.awt.Font("Algerian", 3, 36));
        l5.setForeground(new java.awt.Color(0, 0, 204));
        l5.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));

        l4.setFont(new java.awt.Font("Algerian", 3, 36));
        l4.setForeground(new java.awt.Color(0, 0, 204));
        l4.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));

        l3.setFont(new java.awt.Font("Algerian", 3, 36));
        l3.setForeground(new java.awt.Color(0, 0, 204));
        l3.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));

        l2.setFont(new java.awt.Font("Algerian", 3, 24));
        l2.setForeground(new java.awt.Color(0, 0, 204));
        l2.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));

        l1.setFont(new java.awt.Font("Algerian", 3, 18));
        l1.setForeground(new java.awt.Color(0, 12, 242));
        l1.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(21, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addComponent(l10, javax.swing.GroupLayout.DEFAULT_SIZE, 231, Short.MAX_VALUE)
                        .addComponent(l11, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(l9, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(l8, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 205, Short.MAX_VALUE)
                            .addComponent(l7, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(l6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(10, 10, 10)))
                .addGap(38, 38, 38))
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(l13, javax.swing.GroupLayout.DEFAULT_SIZE, 270, Short.MAX_VALUE)
                .addContainerGap())
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(l12, javax.swing.GroupLayout.DEFAULT_SIZE, 260, Short.MAX_VALUE)
                .addContainerGap())
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(82, 82, 82)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(l3, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 145, Short.MAX_VALUE)
                    .addComponent(l4, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 145, Short.MAX_VALUE)
                    .addComponent(l5, javax.swing.GroupLayout.DEFAULT_SIZE, 145, Short.MAX_VALUE))
                .addGap(63, 63, 63))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(89, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addComponent(l1, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(l2, javax.swing.GroupLayout.PREFERRED_SIZE, 114, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(87, 87, 87))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(l13, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(l12, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(l11, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(l10, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(l9, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(11, 11, 11)
                .addComponent(l8, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(l7, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(l6, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(l5, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(l4, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(l3, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(l2, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(l1, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        n.setFont(new java.awt.Font("Brush Script MT", 2, 36));
        n.setForeground(new java.awt.Color(153, 0, 153));
        n.setText("Next");
        n.setBorder(javax.swing.BorderFactory.createMatteBorder(2, 2, 2, 2, new java.awt.Color(0, 0, 0)));
        n.setEnabled(false);
        n.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                nMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                nMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                nMouseExited(evt);
            }
        });
        n.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nActionPerformed(evt);
            }
        });

        jPanel3.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createMatteBorder(10, 10, 10, 10, new java.awt.Color(0, 0, 0)), "", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.TOP, new java.awt.Font("Chiller", 3, 24), java.awt.Color.red)); // NOI18N
        jPanel3.setEnabled(false);

        pic.setIcon(new ImageIcon("C:\\nm\\kbc.jpg"));

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pic, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 180, Short.MAX_VALUE)
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pic, javax.swing.GroupLayout.DEFAULT_SIZE, 185, Short.MAX_VALUE)
        );

        lll.setIcon(new ImageIcon("C:\\nm\\49B4~1.GIF"));

        jLabel1.setFont(new java.awt.Font("Chiller", 3, 60));
        jLabel1.setForeground(new java.awt.Color(198, 42, 73));
        jLabel1.setText("Kaun Banega Crorepati");

        q.setFont(new java.awt.Font("Matura MT Script Capitals", 2, 18));
        q.setBorder(new javax.swing.border.MatteBorder(null));

        s.setFont(new java.awt.Font("Brush Script MT", 3, 24));
        s.setForeground(new java.awt.Color(0, 153, 0));
        s.setText("Start");
        s.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                sMouseEntered(evt);
            }
        });
        s.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sActionPerformed(evt);
            }
        });

        answ.setFont(new java.awt.Font("Chiller", 3, 36));
        answ.setForeground(new java.awt.Color(255, 0, 0));
        answ.setToolTipText("");

        ansc.setFont(new java.awt.Font("Chiller", 3, 36));
        ansc.setForeground(new java.awt.Color(0, 204, 51));

        s1.setFont(new java.awt.Font("Brush Script MT", 1, 36));
        s1.setForeground(new java.awt.Color(102, 0, 102));
        s1.setText("Submit");
        s1.setBorder(javax.swing.BorderFactory.createMatteBorder(2, 2, 2, 2, new java.awt.Color(0, 0, 0)));
        s1.setEnabled(false);
        s1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                s1MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                s1MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                s1MouseExited(evt);
            }
        });
        s1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                s1ActionPerformed(evt);
            }
        });

        buttonGroup1.add(r1);

        r.setFont(new java.awt.Font("Brush Script MT", 1, 36));
        r.setForeground(new java.awt.Color(102, 0, 102));
        r.setText("Restart");
        r.setBorder(javax.swing.BorderFactory.createMatteBorder(2, 2, 2, 2, new java.awt.Color(0, 0, 0)));
        r.setEnabled(false);
        r.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                rMouseEntered(evt);
            }
        });
        r.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rActionPerformed(evt);
            }
        });

        life.setBackground(new java.awt.Color(226, 223, 214));
        life.setColumns(20);
        life.setEditable(false);
        life.setFont(new java.awt.Font("Chiller", 3, 36));
        life.setForeground(new java.awt.Color(204, 0, 204));
        life.setRows(5);
        jScrollPane1.setViewportView(life);

        n1.setFont(new java.awt.Font("Brush Script MT", 2, 36));
        n1.setForeground(new java.awt.Color(153, 0, 153));
        n1.setText("Quit");
        n1.setBorder(javax.swing.BorderFactory.createMatteBorder(2, 2, 2, 2, new java.awt.Color(0, 0, 0)));
        n1.setEnabled(false);
        n1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                n1ActionPerformed(evt);
            }
        });

        c.setFont(new java.awt.Font("Chiller", 3, 36));
        c.setForeground(new java.awt.Color(204, 153, 255));

        n2.setFont(new java.awt.Font("Brush Script MT", 2, 36));
        n2.setForeground(new java.awt.Color(153, 0, 153));
        n2.setText("Exit");
        n2.setBorder(javax.swing.BorderFactory.createMatteBorder(2, 2, 2, 2, new java.awt.Color(0, 0, 0)));
        n2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                n2ActionPerformed(evt);
            }
        });

        pic2.setIcon(new ImageIcon("C:\\nm\\8455_001.gif"));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addComponent(lll, javax.swing.GroupLayout.PREFERRED_SIZE, 213, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(20, 20, 20)
                        .addComponent(r, javax.swing.GroupLayout.PREFERRED_SIZE, 162, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(60, 60, 60)
                        .addComponent(n1, javax.swing.GroupLayout.PREFERRED_SIZE, 82, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(60, 60, 60)
                        .addComponent(n2, javax.swing.GroupLayout.PREFERRED_SIZE, 82, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(7, 7, 7)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(138, 138, 138)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 490, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(32, 32, 32)
                        .addComponent(s)
                        .addGap(27, 27, 27)
                        .addComponent(answ, javax.swing.GroupLayout.PREFERRED_SIZE, 263, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(10, 10, 10)
                                .addComponent(q, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(4, 4, 4)
                                .addComponent(qq, javax.swing.GroupLayout.PREFERRED_SIZE, 630, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(20, 20, 20)
                                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(30, 30, 30)
                                .addComponent(c, javax.swing.GroupLayout.PREFERRED_SIZE, 611, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(70, 70, 70)
                                        .addComponent(s1, javax.swing.GroupLayout.PREFERRED_SIZE, 111, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(19, 19, 19)
                                        .addComponent(n, javax.swing.GroupLayout.PREFERRED_SIZE, 82, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addComponent(rose, javax.swing.GroupLayout.PREFERRED_SIZE, 280, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(58, 58, 58)
                                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 399, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(51, 51, 51)
                        .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(540, 540, 540)
                        .addComponent(pic2, javax.swing.GroupLayout.PREFERRED_SIZE, 255, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(770, 770, 770)
                        .addComponent(ansc, javax.swing.GroupLayout.PREFERRED_SIZE, 253, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(1060, 1060, 1060)
                        .addComponent(r1))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(lll, javax.swing.GroupLayout.PREFERRED_SIZE, 197, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(21, 21, 21)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(19, 19, 19)
                .addComponent(r)
                .addGap(11, 11, 11)
                .addComponent(n1)
                .addGap(11, 11, 11)
                .addComponent(n2))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(20, 20, 20)
                        .addComponent(s, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(20, 20, 20)
                        .addComponent(answ, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(10, 10, 10)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(30, 30, 30)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(q, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(qq, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(35, 35, 35)
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(6, 6, 6)
                        .addComponent(c, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(38, 38, 38)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(s1)
                                    .addComponent(n))
                                .addGap(11, 11, 11)
                                .addComponent(rose, javax.swing.GroupLayout.PREFERRED_SIZE, 213, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(30, 30, 30)
                                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 220, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, 630, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(90, 90, 90)
                        .addComponent(pic2, javax.swing.GroupLayout.PREFERRED_SIZE, 257, javax.swing.GroupLayout.PREFERRED_SIZE))))
            .addGroup(layout.createSequentialGroup()
                .addGap(50, 50, 50)
                .addComponent(ansc, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addComponent(r1)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
    int cid = 0;
private void sActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sActionPerformed
     n2.setEnabled(false);
    n1.setEnabled(true);

    rose.setIcon(new ImageIcon("C:\\nm\\@ROSE.gif"));
    s.setEnabled(false);

    cid = cid + 1;


    life.setEnabled(true);
    s1.setEnabled(false);
    n.setEnabled(false);
    r.setEnabled(false);

    life.setText("  Question  for " + "\n" + "      Rs. 5,000");
    q.setText("Q 1.");
    qq.setText("The head of Indian Parliament System is the ? ");
    opt1.setText(" Speaker of Lok Sabha");
    opt2.setText(" President ");
    opt3.setText(" Speaker of Rajya Sabha");
    opt4.setText(" Prime Minister ");

    r1.setEnabled(false);
    opt1.setEnabled(true);
    opt2.setEnabled(true);
    opt3.setEnabled(true);
    opt4.setEnabled(true);


// TODO add your handling code here:
}//GEN-LAST:event_sActionPerformed

    private void nActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nActionPerformed
        n1.setEnabled(true);
        n.setEnabled(false);
        s1.setEnabled(false);
        opt1.setEnabled(true);
        opt2.setEnabled(true);
        opt3.setEnabled(true);
        opt4.setEnabled(true);


        r1.setSelected(true);
        opt1.setSelected(false);
        opt2.setSelected(false);
        opt3.setSelected(false);
        opt4.setSelected(false);


        ansc.setText(" ");
        answ.setText(" ");

        cid = cid + 1;

        switch (cid) {




            case 2:
                q.setText("Q 2.");
                qq.setText("The Chemical name of Choroform is ? ");
                opt1.setText(" Sulphuric acid ");
                opt2.setText(" Sodium Chloride");
                opt3.setText(" Trichloromethane ");
                opt4.setText(" Sodium Carbonate ");
                life.setText("  Question  for " + "\n" + "      Rs. 10,000");
                break;

            case 3:
                q.setText("Q 3.");
                qq.setText("In India which source of irrigation is widely used ? ");
                opt1.setText(" Canals");
                opt2.setText(" Wells ");
                opt3.setText(" Rivers");
                opt4.setText(" Tanks ");
                life.setText("  Question  for " + "\n" + "      Rs. 20,000");
                break;

            case 4:
                q.setText("Q 4.");
                qq.setText("Which is considered as the biggest port of India ? ");

                opt1.setText(" Kolkata ");
                opt2.setText(" Cochin");
                opt3.setText(" Chennai");
                opt4.setText(" Mumbai ");
                life.setText("  Question  for " + "\n" + "      Rs. 40,000");
                break;


            case 5:
                q.setText("Q 5.");
                qq.setText("Animals that fed only on dead flesh are -  ");
                pic.setText(" ");
                opt1.setText("Herbivorous");
                opt2.setText(" Carrion-eaters ");
                opt3.setText("Omnivorous ");
                opt4.setText(" Carnivorous ");
                life.setText("  Question  for " + "\n" + "      Rs. 80,000");
                break;


            case 6:
                q.setText("Q  6.");
                qq.setText("A Collection of related file is called -? ");
                pic.setText(" ");
                opt1.setText("Character");
                opt2.setText(" Field ");
                opt3.setText("Database ");
                opt4.setText(" Record ");
                life.setText("  Question  for " + "\n" + "      Rs. 1,60,000");
                break;

            case 7:
                q.setText("Q 7.");
                qq.setText("World Blood Donor Day was observed on : ");
                pic.setText(" ");
                opt1.setText("June 14");
                opt2.setText(" May 5 ");
                opt3.setText("August 19 ");
                opt4.setText(" September 23 ");
                life.setText("  Question  for " + "\n" + "      Rs. 3,20,000");
                break;

            case 8:
                q.setText("Q 8.");
                qq.setText("Nehru Sethu the longest bridge in Asia has been built on the river ? ");
                pic.setText(" ");
                opt1.setText("Yamuna");
                opt2.setText(" Brahmaputra ");
                opt3.setText("The Ganges ");
                opt4.setText(" Sone ");
                life.setText("  Question  for " + "\n" + "      Rs. 6,40,000");
                break;

            case 9:
                q.setText("Q 9.");
                qq.setText("Who won the FIFA Confederation Cup 2013 ?");
                pic.setText(" ");
                opt1.setText("India");
                opt2.setText(" Brazil ");
                opt3.setText("New Zealand ");
                opt4.setText(" West Indies");
                life.setText("  Question  for " + "\n" + "      Rs. 12,50,000");
                break;

            case 10:
                q.setText("Q 10.");
                qq.setText("The Final interpreter of he Indian Constitution is -  ");
                pic.setText(" ");
                opt1.setText("Central Cabinet");
                opt2.setText(" President ");
                opt3.setText("Supreme Court ");
                opt4.setText(" High Court");
                life.setText("  Question  for " + "\n" + "      Rs. 25,00,000");
                break;

            case 11:
                q.setText("Q 11.");
                qq.setText("Mahbashya was written by -  ");
                pic.setText(" ");
                opt1.setText("Patanjali");
                opt2.setText(" Bana ");
                opt3.setText("Manu");
                opt4.setText(" Gargi ");
                life.setText("  Question  for " + "\n" + "      Rs. 50,00,000");
                break;

            case 12:
                q.setText("Q 12.");
                qq.setText("Sher Shah died while fighting in - ");
                pic.setText(" ");
                opt1.setText("Chausa");
                opt2.setText(" Kalinga ");
                opt3.setText("Kalinjar ");
                opt4.setText(" None of the above");
                life.setText("  Question  for " + "\n" + "      Rs. 1 Crore");
                break;



            case 13:
                JOptionPane.showConfirmDialog(null, "Would You Like To Play The JackPot Question ? " + "\n" + "(If You Play Then You can't Quit the game)");
                q.setText("Q 13.");
                qq.setText("Who among the following was the leader of Cabinet Mission ? ");
                pic.setText(" ");
                opt1.setText("Linlithgow");
                opt2.setText(" Stafford Cripps ");
                opt3.setText("A.V. Alexander ");
                opt4.setText("Sir Pethick Lawrence");
                life.setText(" JackPot Question  " + "\n" + "      Rs. 5 Crore");
                n1.setEnabled(false);
                n2.setEnabled(false);
                break;


        }







    // TODO add your handling code here:
    }//GEN-LAST:event_nActionPerformed

    private void s1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_s1ActionPerformed
        n1.setEnabled(false);
        n.setEnabled(true);
        s1.setEnabled(false);
        int ab;
        if (opt1.isSelected()) {
            ab = 1;
        } else if (opt2.isSelected()) {
            ab = 2;
        } else if (opt3.isSelected()) {
            ab = 3;
        } else {
            ab = 4;
        }

        opt1.setEnabled(false);
        opt2.setEnabled(false);
        opt3.setEnabled(false);
        opt4.setEnabled(false);



        if (cid == 1) {
            switch (ab) {
                case 2:
                    ansc.setText(" Correct Answer !");
                    l1.setText(" 5000");
                    life.setText("    Earned" + "\n" + "     Rs. 5000");
                    break;

                default:
                    pic.setIcon(new ImageIcon("C:\\nm\\looser.jpg"));
                    pic2.setIcon(new ImageIcon("C:\\nm\\looser.jpg"));
                    answ.setText(" Wrong Answer !!");
                    life.setText("  OOPS!!! " + "\n" + "        GAME OVER !!" + "\n" + " You Have Earned NThing !!!");
                    n.setEnabled(false);
                    r.setEnabled(true);
                    c.setText("Correct Answer is - 'President'");
                    break;
            }
        } else if (cid == 2) {
            switch (ab) {
                case 3:
                    ansc.setText(" Correct Answer !");
                    life.setText("    Earned" + "\n" + "     Rs. 10,000");
                    l2.setText(" 10,000");
                    break;

                default:
                    pic.setIcon(new ImageIcon("C:\\nm\\looser.jpg"));
                    pic2.setIcon(new ImageIcon("C:\\nm\\looser.jpg"));
                    answ.setText(" Wrong Answer !!");
                    life.setText("  OOPS!!! " + "\n" + "        GAME OVER !!" + "\n" + " You Have Earned NThing !!!");
                    n.setEnabled(false);
                    r.setEnabled(true);
                    r.setEnabled(true);
                    c.setText("Correct Answer is - 'Trichloromethane'");
                    break;
            }
        } else if (cid == 3) {
            switch (ab) {
                case 1:
                    ansc.setText(" Correct Answer !");
                    life.setText("    Earned" + "\n" + "     Rs. 20,000");
                    l3.setText(" 20,000");
                    break;
                default:
                    pic.setIcon(new ImageIcon("C:\\nm\\looser.jpg"));
                    pic2.setIcon(new ImageIcon("C:\\nm\\looser.jpg"));
                    answ.setText(" Wrong Answer !!");
                    life.setText("  OOPS!!! " + "\n" + "        GAME OVER !!" + "\n" + " You Have Earned NThing !!!");
                    n.setEnabled(false);
                    r.setEnabled(true);
                    r.setEnabled(true);
                    c.setText("Correct Answer is - 'Canals'");

                    break;
            }
        } else if (cid == 4) {
            switch (ab) {
                case 4:
                    ansc.setText(" Correct Answer !");
                    life.setText("    Earned" + "\n" + "     Rs. 40,000");
                    l4.setText(" 40,000");
                    break;
                default:
                    pic.setIcon(new ImageIcon("C:\\nm\\looser.jpg"));
                    pic2.setIcon(new ImageIcon("C:\\nm\\looser.jpg"));
                    answ.setText(" Wrong Answer !!");
                    life.setText("  OOPS!!! " + "\n" + "        GAME OVER !!" + "\n" + " You Have Earned NThing !!!");
                    n.setEnabled(false);
                    r.setEnabled(true);
                    r.setEnabled(true);
                    c.setText("Correct Answer is - 'Mumbai'");
                    break;
            }
        } else if (cid == 5) {
            switch (ab) {
                case 2:
                    ansc.setText(" Correct Answer !");
                    life.setText("    Earned" + "\n" + "     Rs. 80,000");
                    l5.setText(" 80,000");
                    break;
                default:
                    pic.setIcon(new ImageIcon("C:\\nm\\looser.jpg"));
                    pic2.setIcon(new ImageIcon("C:\\nm\\looser.jpg"));
                    answ.setText(" Wrong Answer !!");
                    life.setText("  OOPS!!! " + "\n" + "        GAME OVER !!" + "\n" + " You Have Earned NThing !!!");
                    n.setEnabled(false);
                    r.setEnabled(true);
                    r.setEnabled(true);
                    c.setText("Correct Answer is - 'Carrion-eaters'");
                    break;
            }
        } else if (cid == 6) {
            switch (ab) {
                case 3:
                    ansc.setText(" Correct Answer !");
                    life.setText("    Earned" + "\n" + "     Rs. 1,60,000");
                    l6.setText(" 1,60,000");
                    break;
                default:
                    pic.setIcon(new ImageIcon("C:\\nm\\looser.jpg"));
                    pic2.setIcon(new ImageIcon("C:\\nm\\looser.jpg"));
                    answ.setText(" Wrong Answer !!");
                    life.setText("  OOPS!!! " + "\n" + "        GAME OVER !!" + "\n" + " You Have Earned NThing !!!");
                    n.setEnabled(false);
                    r.setEnabled(true);
                    r.setEnabled(true);
                    c.setText("Correct Answer is - 'Database'");
                    break;
            }
        } else if (cid == 7) {
            switch (ab) {
                case 1:
                    ansc.setText(" Correct Answer !");
                    life.setText("    Earned" + "\n" + "     Rs. 3,20,000");
                    l7.setText(" 3,20,000");
                    break;
                default:
                    pic.setIcon(new ImageIcon("C:\\nm\\looser.jpg"));
                    pic2.setIcon(new ImageIcon("C:\\nm\\looser.jpg"));
                    answ.setText(" Wrong Answer !!");
                    life.setText("  OOPS!!! " + "\n" + "        GAME OVER !!" + "\n" + "       " + "You Have Earned" + "\n" + "       " + "Rs. 1,60,000 ");
                    n.setEnabled(false);
                    r.setEnabled(true);
                    r.setEnabled(true);
                    c.setText("Correct Answer is - 'June 14'");
                    break;
            }
        } else if (cid == 8) {
            switch (ab) {
                case 4:
                    ansc.setText(" Correct Answer !");
                    life.setText("    Earned" + "\n" + "     Rs. 6,40,000");
                    l8.setText(" 6,40,000");
                    break;
                default:
                    pic.setIcon(new ImageIcon("C:\\nm\\looser.jpg"));
                    pic2.setIcon(new ImageIcon("C:\\nm\\looser.jpg"));
                    answ.setText(" Wrong Answer !!");
                    life.setText("  OOPS!!! " + "\n" + "        GAME OVER !!" + "\n" + "       " + "You Have Earned" + "\n" + "       " + "Rs. 1,60,000 ");
                    n.setEnabled(false);
                    r.setEnabled(true);
                    r.setEnabled(true);
                    c.setText("Correct Answer is - 'Sone'");
                    break;
            }
        } else if (cid == 9) {
            switch (ab) {
                case 2:
                    ansc.setText(" Correct Answer !");
                    life.setText("    Earned" + "\n" + "     Rs. 12,50,000");
                    l9.setText(" 12,50,000");
                    break;
                default:
                    pic.setIcon(new ImageIcon("C:\\nm\\looser.jpg"));
                    pic2.setIcon(new ImageIcon("C:\\nm\\looser.jpg"));
                    answ.setText(" Wrong Answer !!");
                    life.setText("  OOPS!!! " + "\n" + "        GAME OVER !!" + "\n" + "       " + "You Have Earned" + "\n" + "       " + "Rs. 6,40,000 ");
                    n.setEnabled(false);
                    r.setEnabled(true);
                    r.setEnabled(true);
                    c.setText("Correct Answer is - 'Brazil'");
                    break;
            }
        } else if (cid == 10) {
            switch (ab) {
                case 3:
                    ansc.setText(" Correct Answer !");
                    life.setText("    Earned" + "\n" + "     Rs. 25,00,000");
                    l10.setText(" 25,00,000");
                    break;
                default:
                    pic.setIcon(new ImageIcon("C:\\nm\\looser.jpg"));
                    pic2.setIcon(new ImageIcon("C:\\nm\\looser.jpg"));
                    answ.setText(" Wrong Answer !!");
                    life.setText("  OOPS!!! " + "\n" + "        GAME OVER !!" + "\n" + "       " + "You Have Earned" + "\n" + "       " + "Rs. 6,40,000 ");
                    n.setEnabled(false);
                    r.setEnabled(true);
                    r.setEnabled(true);
                    c.setText("Correct Answer is - 'Supreme Court'");
                    break;
            }
        } else if (cid == 11) {
            switch (ab) {
                case 1:
                    ansc.setText(" Correct Answer !");
                    life.setText("    Earned" + "\n" + "     Rs. 50,00,000");
                    l11.setText(" 50,00,000");
                    break;
                default:
                    pic.setIcon(new ImageIcon("C:\\nm\\looser.jpg"));
                    pic2.setIcon(new ImageIcon("C:\\nm\\looser.jpg"));
                    answ.setText(" Wrong Answer !!");
                    life.setText("  OOPS!!! " + "\n" + "        GAME OVER !!" + "\n" + "       " + "You Have Earned" + "\n" + "       " + "Rs. 25,00,000 ");
                    n.setEnabled(false);
                    r.setEnabled(true);
                    r.setEnabled(true);
                    c.setText("Correct Answer is - 'Patanjali'");
                    break;
            }
        } else if (cid == 12) {
            switch (ab) {
                case 3:
                    ansc.setText(" Correct Answer !");
                    life.setText("    Earned" + "\n" + "     Rs. 1 Crore");
                    l12.setText("     1 crore");
                    life.setText(" Congratulations ! " + "\n" + "      You became Crorepati" + "\n" + "           Rs. 1 Crore");
                  pic2.setIcon(new ImageIcon("C:\\nm\\kbc.jpg"));
                    break;
                default:
                    pic.setIcon(new ImageIcon("C:\\nm\\looser.jpg"));
                    pic2.setIcon(new ImageIcon("C:\\nm\\looser.jpg"));
                    answ.setText(" Wrong Answer !!");
                    life.setText("  OOPS!!! " + "\n" + "        GAME OVER !!" + "\n" + "       " + "You Have Earned" + "\n" + "       " + "Rs. 25,00,000 ");
                    n.setEnabled(false);
                    r.setEnabled(true);
                    r.setEnabled(true);
                    c.setText("Correct Answer is - 'Kalinjar'");
                    break;
            }
        } else if (cid == 13) {
            switch (ab) {
                case 2:
                    ansc.setText(" Correct Answer !");
                    life.setText(" Congratulations ! " + "\n" + "      You have Won the Game" + "\n" + "           Rs. 5 Crore");
                    l13.setText("     5 crore");
                    n.setEnabled(false);
                    r.setEnabled(true);
                    rose.setIcon(new ImageIcon("C:\\nm\\kbc.jpg"));
                    break;
                default:
                    pic.setIcon(new ImageIcon("C:\\nm\\looser.jpg"));
                    pic2.setIcon(new ImageIcon("C:\\nm\\looser.jpg"));
                    answ.setText(" Wrong Answer !!");
                    life.setText("  OOPS!!! " + "\n" + "        GAME OVER !!" + "\n" + "       " + "You Have Earned" + "\n" + "       " + "Rs. 25,00,000 ");
                    n.setEnabled(false);

                    r.setEnabled(true);
                    c.setText("Correct Answer is - 'Stafford Cripps'");
                    break;
            }
        }



    // TODO add your handling code here:
    }//GEN-LAST:event_s1ActionPerformed

    private void rActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rActionPerformed

        pic.setIcon(new ImageIcon("C:\\nm\\kbc.jpg"));
        pic2.setIcon(new ImageIcon("C:\\nm\\8455_001.gif"));
        n2.setEnabled(true);
        s.setEnabled(true);
        c.setText(" ");
        r.setEnabled(false);
        cid = 0;
        s1.setEnabled(false);
        n.setEnabled(false);
        l1.setText(" ");
        l2.setText(" ");
        l3.setText(" ");
        l4.setText(" ");
        l5.setText(" ");
        l6.setText(" ");
        l7.setText(" ");
        l8.setText(" ");
        l9.setText(" ");
        l10.setText(" ");
        l11.setText(" ");
        l12.setText(" ");
        l13.setText(" ");
        q.setText(" ");
        qq.setText(" ");
        ansc.setText(" ");
        answ.setText(" ");
        opt1.setText(" ");
        opt2.setText(" ");
        opt3.setText(" ");
        opt4.setText(" ");
        r1.setSelected(true);
        opt1.setSelected(false);
        opt2.setSelected(false);
        opt3.setSelected(false);
        opt4.setSelected(false);
        life.setText(" ");

// TODO add your handling code here:
}//GEN-LAST:event_rActionPerformed

    private void n1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_n1ActionPerformed
n2.setEnabled(true);
        switch (cid) {
            case 2:
                life.setText(" Thankyou for Playing " + "\n" + "            KBC" + "\n" + "       " + "You Have Earned" + "\n" + "       " + "Rs. 5,000 ");
                c.setText("Correct Answer is - 'Trichloromethane'");
                break;
            case 3:
                life.setText(" Thankyou for Playing " + "\n" + "            KBC" + "\n" + "       " + "You Have Earned" + "\n" + "       " + "Rs. 10,000 ");
                c.setText("Correct Answer is - 'Canals'");
                break;
            case 4:
                life.setText(" Thankyou for Playing " + "\n" + "            KBC" + "\n" + "       " + "You Have Earned" + "\n" + "       " + "Rs. 20,000 ");
                c.setText("Correct Answer is - 'Mumbai'");
                break;
            case 5:
                life.setText(" Thankyou for Playing " + "\n" + "            KBC" + "\n" + "       " + "You Have Earned" + "\n" + "       " + "Rs. 40,000 ");
                c.setText("Correct Answer is - 'Carrion-eaters'");
                break;
            case 6:
                life.setText(" Thankyou for Playing " + "\n" + "            KBC" + "\n" + "       " + "You Have Earned" + "\n" + "       " + "Rs. 80,000 ");
                c.setText("Correct Answer is - 'Database'");
                break;
            case 7:
                life.setText(" Thankyou for Playing " + "\n" + "            KBC" + "\n" + "       " + "You Have Earned" + "\n" + "       " + "Rs. 1,60,000 ");
                c.setText("Correct Answer is - 'June 14'");
                break;
            case 8:
                life.setText(" Thankyou for Playing " + "\n" + "            KBC" + "\n" + "       " + "You Have Earned" + "\n" + "       " + "Rs. 3,20,000 ");
                c.setText("Correct Answer is - 'Sone'");
                break;
            case 9:
                life.setText(" Thankyou for Playing " + "\n" + "            KBC" + "\n" + "       " + "You Have Earned" + "\n" + "       " + "Rs. 6,40,000 ");
                c.setText("Correct Answer is - 'Brazil'");
                break;
            case 10:
                life.setText(" Thankyou for Playing " + "\n" + "            KBC" + "\n" + "       " + "You Have Earned" + "\n" + "       " + "Rs. 12,50,000 ");
                c.setText("Correct Answer is - 'Supreme Court'");
                break;
            case 11:
                life.setText(" Thankyou for Playing " + "\n" + "            KBC" + "\n" + "       " + "You Have Earned" + "\n" + "       " + "Rs. 25,00,000 ");
                c.setText("Correct Answer is - 'Patanjali'");
                break;
            case 12:
                life.setText(" Thankyou for Playing " + "\n" + "            KBC" + "\n" + "       " + "You Have Earned" + "\n" + "       " + "Rs. 50,00,000 ");
                c.setText("Correct Answer is - 'Kalinjar'");
                break;
            case 1:
                life.setText(" Thankyou for Playing " + "\n" + "            KBC" + "\n" + "       " + "You Have Earned" + "\n" + "       " + "NThing !!! ");
                c.setText("Correct Answer is - 'President'");


        }
        s1.setEnabled(false);
        n.setEnabled(false);
        r.setEnabled(true);
        opt1.setEnabled(false);
        opt2.setEnabled(false);
        opt3.setEnabled(false);
        opt4.setEnabled(false);

// TODO add your handling code here:
    }//GEN-LAST:event_n1ActionPerformed

    private void opt2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_opt2ActionPerformed
        s1.setEnabled(true);
// TODO add your handling code here:
    }//GEN-LAST:event_opt2ActionPerformed

    private void opt4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_opt4ActionPerformed
        s1.setEnabled(true);        // TODO add your handling code here:
    }//GEN-LAST:event_opt4ActionPerformed

    private void opt1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_opt1ActionPerformed
        s1.setEnabled(true);        // TODO add your handling code here:
    }//GEN-LAST:event_opt1ActionPerformed

    private void opt3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_opt3ActionPerformed
        s1.setEnabled(true);        // TODO add your handling code here:
    }//GEN-LAST:event_opt3ActionPerformed

    private void n2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_n2ActionPerformed
        JOptionPane.showMessageDialog(null, "Good Bye !!" + "\n " + "     Take Care");
       dispose();       // TODO add your handling code here:
    }//GEN-LAST:event_n2ActionPerformed

    private void s1MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_s1MouseEntered

// TODO add your handling code here:
    }//GEN-LAST:event_s1MouseEntered

    private void s1MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_s1MouseExited
    // TODO add your handling code here:
    }//GEN-LAST:event_s1MouseExited

    private void nMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_nMouseEntered









   // TODO add your handling code here:
    }//GEN-LAST:event_nMouseEntered

    private void nMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_nMouseExited
     // TODO add your handling code here:
    }//GEN-LAST:event_nMouseExited

    private void nMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_nMouseClicked
    // TODO add your handling code here:
    }//GEN-LAST:event_nMouseClicked

    private void s1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_s1MouseClicked
    // TODO add your handling code here:
    }//GEN-LAST:event_s1MouseClicked

    private void sMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_sMouseEntered
     // TODO add your handling code here:
    }//GEN-LAST:event_sMouseEntered

    private void opt2MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_opt2MouseEntered
        // TODO add your handling code here:
    }//GEN-LAST:event_opt2MouseEntered

    private void opt1MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_opt1MouseEntered
  // TODO add your handling code here:
    }//GEN-LAST:event_opt1MouseEntered

    private void opt3MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_opt3MouseEntered
         // TODO add your handling code here:
    }//GEN-LAST:event_opt3MouseEntered

    private void opt4MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_opt4MouseEntered
           // TODO add your handling code here:
    }//GEN-LAST:event_opt4MouseEntered

    private void rMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_rMouseEntered
        // TODO add your handling code here:
    }//GEN-LAST:event_rMouseEntered

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {

            public void run() {
                new game().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel ansc;
    private javax.swing.JLabel answ;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JLabel c;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel l1;
    private javax.swing.JLabel l10;
    private javax.swing.JLabel l11;
    private javax.swing.JLabel l12;
    private javax.swing.JLabel l13;
    private javax.swing.JLabel l2;
    private javax.swing.JLabel l3;
    private javax.swing.JLabel l4;
    private javax.swing.JLabel l5;
    private javax.swing.JLabel l6;
    private javax.swing.JLabel l7;
    private javax.swing.JLabel l8;
    private javax.swing.JLabel l9;
    private javax.swing.JTextArea life;
    private javax.swing.JLabel lll;
    private javax.swing.JButton n;
    private javax.swing.JButton n1;
    private javax.swing.JButton n2;
    private javax.swing.JRadioButton opt1;
    private javax.swing.JRadioButton opt2;
    private javax.swing.JRadioButton opt3;
    private javax.swing.JRadioButton opt4;
    private javax.swing.JLabel pic;
    private javax.swing.JLabel pic2;
    private javax.swing.JLabel q;
    private javax.swing.JLabel qq;
    private javax.swing.JButton r;
    private javax.swing.JRadioButton r1;
    private javax.swing.JLabel rose;
    private javax.swing.JButton s;
    private javax.swing.JButton s1;
    // End of variables declaration//GEN-END:variables
}
